name: Convert Jupyter Notebook to HTML

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Jupyter
        run: pip install jupyter

      - name: Convert Notebook
        run: jupyter nbconvert --to html demo.ipynb

      - name: Move HTML to Docs
        run: mv demo.html docs/

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/demo.html
          git commit -m "Auto-update notebook HTML"
          git push
